Generate reference documentation at build time
This replaces the use of
`@enterprise-contract/reference-antora-extension` with code generation
that is run at build time. The documentation should resemble the
existing documentation generated at website build time, only the point
at which the documentation is generated has changed. Also the
documentation is now versioned in the git repository, so a check was
added to make sure the documentation is up to date, i.e. doesn't need to
be regenerated.

Reference: EC-513

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -57,6 +57,18 @@ jobs:
           go-version-file: go.mod
           cache: false
 
+      - name: Generate
+        run: make generate
+
+      - name: Check for uncommitted changes
+        run: |
+          if ! git diff --exit-code -s; then
+            for f in $(git diff --exit-code --name-only); do
+              echo "::error file=$f,line=1,col=1,endColumn=1::File was modified in build"
+            done
+            exit 1
+          fi
+
       - name: Test
         run: make test
 
